version: "3"

networks:
  default:
    external:
      name: microservices

services:

  traefik:
    image: traefik
    command: --api --docker
    ports:
      - "8001:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
